spring.application.name=ecommerce-zapateria
app.security.jwt.secret=zapateria-ecommerce-uade-secret-key-for-hs256-local-development
app.security.jwt.access-token-ttl-minutes=15
app.security.jwt.refresh-token-ttl-days=7
